AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation template to create an EC2 instance with a security group allowing SSH access."

Parameters:
  VPCId:
    Type: AWS::EC2::VPC::Id
    Description: "The ID of the VPC where the security group and instance will be created."

  SSHLocation:
    Type: String
    Description: "The IP address range that is allowed to SSH to the EC2 instance (CIDR format, e.g., 0.0.0.0/0 for all IPs)."
    Default: "10.0.0.0/16"
    AllowedPattern: "(\\d{1,3}\\.){3}\\d{1,3}/\\d{1,2}"
    ConstraintDescription: "Must be a valid CIDR range."

Resources:
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: "Enable SSH access via port 22"
      VpcId: vpc-048e7cd944c725e29
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref SSHLocation

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: key-06apr  # Replace with your existing EC2 key pair
      ImageId: ami-002f6e91abff6eb96  # Replace with a valid AMI ID for your region
      SecurityGroupIds:
        - !Ref MySecurityGroup
      SubnetId: subnet-0462c3a6448822b45
      
Outputs:
  InstanceId:
    Description: "The ID of the created EC2 instance"
    Value: !Ref MyEC2Instance

  SecurityGroupId:
    Description: "The ID of the security group"
    Value: !Ref MySecurityGroup
